name: Build

on:
  push:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      devices: ${{ steps.devices.outputs.devices }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Define devices
        id: devices
        run: |
          cat manifest.xml | grep -oP 'product id="\K[^"]+' | sed 's/.*/"&"/' | paste -sd, - | sed 's/.*/[&]/' | sed 's/.*/devices=&/' >> "$GITHUB_OUTPUT"

  logs:
    name: Lint job
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
       matrix:
         device: ${{ fromJSON(needs.define-matrix.outputs.devices) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate key
        run: | 
          openssl genrsa -out developer_key.pem 4096
          openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt
      - name: Build
        uses: blackshadev/garmin-connectiq-build-action@8.4.0
        with:
          projectJungle: ./monkey.jungle
          developerKey: ./developer_key.der
          outputPath: ${{ matrix.device }}.prg
          device: ${{ matrix.device }}
          typeCheck: '0'
